# Generated by Django 4.2.10 on 2024-02-21 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='event-images'),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='events',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.categories'),
        ),
    ]
